@echo off
FOR /R .\ %%I IN (.\) DO (
     del "%%~dpI*.BAK"
     del "%%~dpI*.sct" 
     del "%%~dpI*.iex" 
     del "%%~dpI*.mco" 
     del "%%~dpI*.lst" 
     del "%%~dpI*.i" 
     del "%%~dpI*.__i" 
     del "%%~dpI*.o" 
     del "%%~dpI*.d" 
     del "%%~dpI*.crf" 
     del "%%~dpI*.tra" 
     del "%%~dpI*.lnp" 
     del "%%~dpI*.plg" 
     del "%%~dpI*.dep" 
     del "%%~dpI*.140_*"
     del "%%~dpI*.build_log*"
     del "%%~dpI*.map"
     del "%%~dpI*._2i"
     del "%%~dpI*.axf"
     del "%%~dpI*.htm"
     del "%%~dpI*.l2p"
     del "%%~dpI*.fed"
 )
